{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "topic.prefix": "_topic_",
  "tasks.max":1,
  "table.types":"VIEW",
  "query": "SELECT * FROM TITLE_DISCOVERY_VIEW",
  "poll.interval.ms": "300000",
  "connection.password": "_password_",
  "connection.user": "_username_",
  "connection.url": "_connection_",
  "mode": "timestamp+incrementing",
  "timestamp.column.name": "LAST_UPDATE_DATETIME",
  "incrementing.column.name": "TITLE_ID",
  "numeric.mapping":"best_fit",
  "validate.non.null": "false",
  "key.converter": "org.apache.kafka.connect.json.JsonConverter",
  "key.converter.schemas.enable":"false",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.schemas.enable": "false",
  "transforms":"createKey,extractInt",
  "transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
  "transforms.createKey.fields":"TITLE_ID",
  "transforms.extractInt.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
  "transforms.extractInt.field":"TITLE_ID",
  "errors.retry.timeout": "-1",
  "errors.retry.delay.max.ms": "30000",
  "errors.log.enable": "true",
  "errors.log.include.messages": "false",
  "errors.tolerance": "all"
}
