/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.streams.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EnrichedOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -901208525857000178L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnrichedOrder\",\"namespace\":\"io.confluent.examples.streams.avro\",\"fields\":[{\"name\":\"product\",\"type\":{\"type\":\"record\",\"name\":\"Product\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"supplier_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"customer\",\"type\":{\"type\":\"record\",\"name\":\"Customer\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gender\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"region\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"order\",\"type\":{\"type\":\"record\",\"name\":\"Order\",\"fields\":[{\"name\":\"customer_id\",\"type\":\"long\"},{\"name\":\"product_id\",\"type\":\"long\"},{\"name\":\"time_order_placed_at\",\"type\":\"long\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EnrichedOrder> ENCODER =
      new BinaryMessageEncoder<EnrichedOrder>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EnrichedOrder> DECODER =
      new BinaryMessageDecoder<EnrichedOrder>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EnrichedOrder> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EnrichedOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EnrichedOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EnrichedOrder>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EnrichedOrder to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EnrichedOrder from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EnrichedOrder instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EnrichedOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public io.confluent.examples.streams.avro.Product product;
  @Deprecated public io.confluent.examples.streams.avro.Customer customer;
  @Deprecated public io.confluent.examples.streams.avro.Order order;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EnrichedOrder() {}

  /**
   * All-args constructor.
   * @param product The new value for product
   * @param customer The new value for customer
   * @param order The new value for order
   */
  public EnrichedOrder(io.confluent.examples.streams.avro.Product product, io.confluent.examples.streams.avro.Customer customer, io.confluent.examples.streams.avro.Order order) {
    this.product = product;
    this.customer = customer;
    this.order = order;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product;
    case 1: return customer;
    case 2: return order;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product = (io.confluent.examples.streams.avro.Product)value$; break;
    case 1: customer = (io.confluent.examples.streams.avro.Customer)value$; break;
    case 2: order = (io.confluent.examples.streams.avro.Order)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'product' field.
   * @return The value of the 'product' field.
   */
  public io.confluent.examples.streams.avro.Product getProduct() {
    return product;
  }


  /**
   * Sets the value of the 'product' field.
   * @param value the value to set.
   */
  public void setProduct(io.confluent.examples.streams.avro.Product value) {
    this.product = value;
  }

  /**
   * Gets the value of the 'customer' field.
   * @return The value of the 'customer' field.
   */
  public io.confluent.examples.streams.avro.Customer getCustomer() {
    return customer;
  }


  /**
   * Sets the value of the 'customer' field.
   * @param value the value to set.
   */
  public void setCustomer(io.confluent.examples.streams.avro.Customer value) {
    this.customer = value;
  }

  /**
   * Gets the value of the 'order' field.
   * @return The value of the 'order' field.
   */
  public io.confluent.examples.streams.avro.Order getOrder() {
    return order;
  }


  /**
   * Sets the value of the 'order' field.
   * @param value the value to set.
   */
  public void setOrder(io.confluent.examples.streams.avro.Order value) {
    this.order = value;
  }

  /**
   * Creates a new EnrichedOrder RecordBuilder.
   * @return A new EnrichedOrder RecordBuilder
   */
  public static io.confluent.examples.streams.avro.EnrichedOrder.Builder newBuilder() {
    return new io.confluent.examples.streams.avro.EnrichedOrder.Builder();
  }

  /**
   * Creates a new EnrichedOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EnrichedOrder RecordBuilder
   */
  public static io.confluent.examples.streams.avro.EnrichedOrder.Builder newBuilder(io.confluent.examples.streams.avro.EnrichedOrder.Builder other) {
    if (other == null) {
      return new io.confluent.examples.streams.avro.EnrichedOrder.Builder();
    } else {
      return new io.confluent.examples.streams.avro.EnrichedOrder.Builder(other);
    }
  }

  /**
   * Creates a new EnrichedOrder RecordBuilder by copying an existing EnrichedOrder instance.
   * @param other The existing instance to copy.
   * @return A new EnrichedOrder RecordBuilder
   */
  public static io.confluent.examples.streams.avro.EnrichedOrder.Builder newBuilder(io.confluent.examples.streams.avro.EnrichedOrder other) {
    if (other == null) {
      return new io.confluent.examples.streams.avro.EnrichedOrder.Builder();
    } else {
      return new io.confluent.examples.streams.avro.EnrichedOrder.Builder(other);
    }
  }

  /**
   * RecordBuilder for EnrichedOrder instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnrichedOrder>
    implements org.apache.avro.data.RecordBuilder<EnrichedOrder> {

    private io.confluent.examples.streams.avro.Product product;
    private io.confluent.examples.streams.avro.Product.Builder productBuilder;
    private io.confluent.examples.streams.avro.Customer customer;
    private io.confluent.examples.streams.avro.Customer.Builder customerBuilder;
    private io.confluent.examples.streams.avro.Order order;
    private io.confluent.examples.streams.avro.Order.Builder orderBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.examples.streams.avro.EnrichedOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.product)) {
        this.product = data().deepCopy(fields()[0].schema(), other.product);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasProductBuilder()) {
        this.productBuilder = io.confluent.examples.streams.avro.Product.newBuilder(other.getProductBuilder());
      }
      if (isValidValue(fields()[1], other.customer)) {
        this.customer = data().deepCopy(fields()[1].schema(), other.customer);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasCustomerBuilder()) {
        this.customerBuilder = io.confluent.examples.streams.avro.Customer.newBuilder(other.getCustomerBuilder());
      }
      if (isValidValue(fields()[2], other.order)) {
        this.order = data().deepCopy(fields()[2].schema(), other.order);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasOrderBuilder()) {
        this.orderBuilder = io.confluent.examples.streams.avro.Order.newBuilder(other.getOrderBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing EnrichedOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.examples.streams.avro.EnrichedOrder other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.product)) {
        this.product = data().deepCopy(fields()[0].schema(), other.product);
        fieldSetFlags()[0] = true;
      }
      this.productBuilder = null;
      if (isValidValue(fields()[1], other.customer)) {
        this.customer = data().deepCopy(fields()[1].schema(), other.customer);
        fieldSetFlags()[1] = true;
      }
      this.customerBuilder = null;
      if (isValidValue(fields()[2], other.order)) {
        this.order = data().deepCopy(fields()[2].schema(), other.order);
        fieldSetFlags()[2] = true;
      }
      this.orderBuilder = null;
    }

    /**
      * Gets the value of the 'product' field.
      * @return The value.
      */
    public io.confluent.examples.streams.avro.Product getProduct() {
      return product;
    }


    /**
      * Sets the value of the 'product' field.
      * @param value The value of 'product'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder setProduct(io.confluent.examples.streams.avro.Product value) {
      validate(fields()[0], value);
      this.productBuilder = null;
      this.product = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'product' field has been set.
      * @return True if the 'product' field has been set, false otherwise.
      */
    public boolean hasProduct() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'product' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.confluent.examples.streams.avro.Product.Builder getProductBuilder() {
      if (productBuilder == null) {
        if (hasProduct()) {
          setProductBuilder(io.confluent.examples.streams.avro.Product.newBuilder(product));
        } else {
          setProductBuilder(io.confluent.examples.streams.avro.Product.newBuilder());
        }
      }
      return productBuilder;
    }

    /**
     * Sets the Builder instance for the 'product' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder setProductBuilder(io.confluent.examples.streams.avro.Product.Builder value) {
      clearProduct();
      productBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'product' field has an active Builder instance
     * @return True if the 'product' field has an active Builder instance
     */
    public boolean hasProductBuilder() {
      return productBuilder != null;
    }

    /**
      * Clears the value of the 'product' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder clearProduct() {
      product = null;
      productBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer' field.
      * @return The value.
      */
    public io.confluent.examples.streams.avro.Customer getCustomer() {
      return customer;
    }


    /**
      * Sets the value of the 'customer' field.
      * @param value The value of 'customer'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder setCustomer(io.confluent.examples.streams.avro.Customer value) {
      validate(fields()[1], value);
      this.customerBuilder = null;
      this.customer = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customer' field has been set.
      * @return True if the 'customer' field has been set, false otherwise.
      */
    public boolean hasCustomer() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'customer' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.confluent.examples.streams.avro.Customer.Builder getCustomerBuilder() {
      if (customerBuilder == null) {
        if (hasCustomer()) {
          setCustomerBuilder(io.confluent.examples.streams.avro.Customer.newBuilder(customer));
        } else {
          setCustomerBuilder(io.confluent.examples.streams.avro.Customer.newBuilder());
        }
      }
      return customerBuilder;
    }

    /**
     * Sets the Builder instance for the 'customer' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder setCustomerBuilder(io.confluent.examples.streams.avro.Customer.Builder value) {
      clearCustomer();
      customerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'customer' field has an active Builder instance
     * @return True if the 'customer' field has an active Builder instance
     */
    public boolean hasCustomerBuilder() {
      return customerBuilder != null;
    }

    /**
      * Clears the value of the 'customer' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder clearCustomer() {
      customer = null;
      customerBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'order' field.
      * @return The value.
      */
    public io.confluent.examples.streams.avro.Order getOrder() {
      return order;
    }


    /**
      * Sets the value of the 'order' field.
      * @param value The value of 'order'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder setOrder(io.confluent.examples.streams.avro.Order value) {
      validate(fields()[2], value);
      this.orderBuilder = null;
      this.order = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'order' field has been set.
      * @return True if the 'order' field has been set, false otherwise.
      */
    public boolean hasOrder() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'order' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.confluent.examples.streams.avro.Order.Builder getOrderBuilder() {
      if (orderBuilder == null) {
        if (hasOrder()) {
          setOrderBuilder(io.confluent.examples.streams.avro.Order.newBuilder(order));
        } else {
          setOrderBuilder(io.confluent.examples.streams.avro.Order.newBuilder());
        }
      }
      return orderBuilder;
    }

    /**
     * Sets the Builder instance for the 'order' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder setOrderBuilder(io.confluent.examples.streams.avro.Order.Builder value) {
      clearOrder();
      orderBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'order' field has an active Builder instance
     * @return True if the 'order' field has an active Builder instance
     */
    public boolean hasOrderBuilder() {
      return orderBuilder != null;
    }

    /**
      * Clears the value of the 'order' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.EnrichedOrder.Builder clearOrder() {
      order = null;
      orderBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EnrichedOrder build() {
      try {
        EnrichedOrder record = new EnrichedOrder();
        if (productBuilder != null) {
          try {
            record.product = this.productBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("product"));
            throw e;
          }
        } else {
          record.product = fieldSetFlags()[0] ? this.product : (io.confluent.examples.streams.avro.Product) defaultValue(fields()[0]);
        }
        if (customerBuilder != null) {
          try {
            record.customer = this.customerBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("customer"));
            throw e;
          }
        } else {
          record.customer = fieldSetFlags()[1] ? this.customer : (io.confluent.examples.streams.avro.Customer) defaultValue(fields()[1]);
        }
        if (orderBuilder != null) {
          try {
            record.order = this.orderBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("order"));
            throw e;
          }
        } else {
          record.order = fieldSetFlags()[2] ? this.order : (io.confluent.examples.streams.avro.Order) defaultValue(fields()[2]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EnrichedOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<EnrichedOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EnrichedOrder>
    READER$ = (org.apache.avro.io.DatumReader<EnrichedOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.product.customEncode(out);

    this.customer.customEncode(out);

    this.order.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.product == null) {
        this.product = new io.confluent.examples.streams.avro.Product();
      }
      this.product.customDecode(in);

      if (this.customer == null) {
        this.customer = new io.confluent.examples.streams.avro.Customer();
      }
      this.customer.customDecode(in);

      if (this.order == null) {
        this.order = new io.confluent.examples.streams.avro.Order();
      }
      this.order.customDecode(in);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.product == null) {
            this.product = new io.confluent.examples.streams.avro.Product();
          }
          this.product.customDecode(in);
          break;

        case 1:
          if (this.customer == null) {
            this.customer = new io.confluent.examples.streams.avro.Customer();
          }
          this.customer.customDecode(in);
          break;

        case 2:
          if (this.order == null) {
            this.order = new io.confluent.examples.streams.avro.Order();
          }
          this.order.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










