/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.streams.avro.microservices;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderValidation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1943233104129539061L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderValidation\",\"namespace\":\"io.confluent.examples.streams.avro.microservices\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"checkType\",\"type\":{\"type\":\"enum\",\"name\":\"OrderValidationType\",\"symbols\":[\"INVENTORY_CHECK\",\"FRAUD_CHECK\",\"ORDER_DETAILS_CHECK\"]}},{\"name\":\"validationResult\",\"type\":{\"type\":\"enum\",\"name\":\"OrderValidationResult\",\"symbols\":[\"PASS\",\"FAIL\",\"ERROR\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderValidation> ENCODER =
      new BinaryMessageEncoder<OrderValidation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderValidation> DECODER =
      new BinaryMessageDecoder<OrderValidation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderValidation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderValidation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderValidation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderValidation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderValidation from a ByteBuffer. */
  public static OrderValidation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String orderId;
  @Deprecated public io.confluent.examples.streams.avro.microservices.OrderValidationType checkType;
  @Deprecated public io.confluent.examples.streams.avro.microservices.OrderValidationResult validationResult;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderValidation() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param checkType The new value for checkType
   * @param validationResult The new value for validationResult
   */
  public OrderValidation(java.lang.String orderId, io.confluent.examples.streams.avro.microservices.OrderValidationType checkType, io.confluent.examples.streams.avro.microservices.OrderValidationResult validationResult) {
    this.orderId = orderId;
    this.checkType = checkType;
    this.validationResult = validationResult;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return checkType;
    case 2: return validationResult;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.String)value$; break;
    case 1: checkType = (io.confluent.examples.streams.avro.microservices.OrderValidationType)value$; break;
    case 2: validationResult = (io.confluent.examples.streams.avro.microservices.OrderValidationResult)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'checkType' field.
   * @return The value of the 'checkType' field.
   */
  public io.confluent.examples.streams.avro.microservices.OrderValidationType getCheckType() {
    return checkType;
  }

  /**
   * Sets the value of the 'checkType' field.
   * @param value the value to set.
   */
  public void setCheckType(io.confluent.examples.streams.avro.microservices.OrderValidationType value) {
    this.checkType = value;
  }

  /**
   * Gets the value of the 'validationResult' field.
   * @return The value of the 'validationResult' field.
   */
  public io.confluent.examples.streams.avro.microservices.OrderValidationResult getValidationResult() {
    return validationResult;
  }

  /**
   * Sets the value of the 'validationResult' field.
   * @param value the value to set.
   */
  public void setValidationResult(io.confluent.examples.streams.avro.microservices.OrderValidationResult value) {
    this.validationResult = value;
  }

  /**
   * Creates a new OrderValidation RecordBuilder.
   * @return A new OrderValidation RecordBuilder
   */
  public static io.confluent.examples.streams.avro.microservices.OrderValidation.Builder newBuilder() {
    return new io.confluent.examples.streams.avro.microservices.OrderValidation.Builder();
  }

  /**
   * Creates a new OrderValidation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderValidation RecordBuilder
   */
  public static io.confluent.examples.streams.avro.microservices.OrderValidation.Builder newBuilder(io.confluent.examples.streams.avro.microservices.OrderValidation.Builder other) {
    return new io.confluent.examples.streams.avro.microservices.OrderValidation.Builder(other);
  }

  /**
   * Creates a new OrderValidation RecordBuilder by copying an existing OrderValidation instance.
   * @param other The existing instance to copy.
   * @return A new OrderValidation RecordBuilder
   */
  public static io.confluent.examples.streams.avro.microservices.OrderValidation.Builder newBuilder(io.confluent.examples.streams.avro.microservices.OrderValidation other) {
    return new io.confluent.examples.streams.avro.microservices.OrderValidation.Builder(other);
  }

  /**
   * RecordBuilder for OrderValidation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderValidation>
    implements org.apache.avro.data.RecordBuilder<OrderValidation> {

    private java.lang.String orderId;
    private io.confluent.examples.streams.avro.microservices.OrderValidationType checkType;
    private io.confluent.examples.streams.avro.microservices.OrderValidationResult validationResult;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.examples.streams.avro.microservices.OrderValidation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.checkType)) {
        this.checkType = data().deepCopy(fields()[1].schema(), other.checkType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.validationResult)) {
        this.validationResult = data().deepCopy(fields()[2].schema(), other.validationResult);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderValidation instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.examples.streams.avro.microservices.OrderValidation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.checkType)) {
        this.checkType = data().deepCopy(fields()[1].schema(), other.checkType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.validationResult)) {
        this.validationResult = data().deepCopy(fields()[2].schema(), other.validationResult);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidation.Builder setOrderId(java.lang.String value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidation.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'checkType' field.
      * @return The value.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidationType getCheckType() {
      return checkType;
    }

    /**
      * Sets the value of the 'checkType' field.
      * @param value The value of 'checkType'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidation.Builder setCheckType(io.confluent.examples.streams.avro.microservices.OrderValidationType value) {
      validate(fields()[1], value);
      this.checkType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'checkType' field has been set.
      * @return True if the 'checkType' field has been set, false otherwise.
      */
    public boolean hasCheckType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'checkType' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidation.Builder clearCheckType() {
      checkType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'validationResult' field.
      * @return The value.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidationResult getValidationResult() {
      return validationResult;
    }

    /**
      * Sets the value of the 'validationResult' field.
      * @param value The value of 'validationResult'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidation.Builder setValidationResult(io.confluent.examples.streams.avro.microservices.OrderValidationResult value) {
      validate(fields()[2], value);
      this.validationResult = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'validationResult' field has been set.
      * @return True if the 'validationResult' field has been set, false otherwise.
      */
    public boolean hasValidationResult() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'validationResult' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderValidation.Builder clearValidationResult() {
      validationResult = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderValidation build() {
      try {
        OrderValidation record = new OrderValidation();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.String) defaultValue(fields()[0]);
        record.checkType = fieldSetFlags()[1] ? this.checkType : (io.confluent.examples.streams.avro.microservices.OrderValidationType) defaultValue(fields()[1]);
        record.validationResult = fieldSetFlags()[2] ? this.validationResult : (io.confluent.examples.streams.avro.microservices.OrderValidationResult) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderValidation>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderValidation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderValidation>
    READER$ = (org.apache.avro.io.DatumReader<OrderValidation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
