/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.streams.avro.microservices;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderEnriched extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -254226944736446523L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderEnriched\",\"namespace\":\"io.confluent.examples.streams.avro.microservices\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"customerId\",\"type\":\"long\"},{\"name\":\"customerLevel\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderEnriched> ENCODER =
      new BinaryMessageEncoder<OrderEnriched>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderEnriched> DECODER =
      new BinaryMessageDecoder<OrderEnriched>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderEnriched> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderEnriched> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderEnriched> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderEnriched>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderEnriched to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderEnriched from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderEnriched instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderEnriched fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public long customerId;
  @Deprecated public java.lang.String customerLevel;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderEnriched() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param customerId The new value for customerId
   * @param customerLevel The new value for customerLevel
   */
  public OrderEnriched(java.lang.String id, java.lang.Long customerId, java.lang.String customerLevel) {
    this.id = id;
    this.customerId = customerId;
    this.customerLevel = customerLevel;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return customerId;
    case 2: return customerLevel;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: customerId = (java.lang.Long)value$; break;
    case 2: customerLevel = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public long getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(long value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'customerLevel' field.
   * @return The value of the 'customerLevel' field.
   */
  public java.lang.String getCustomerLevel() {
    return customerLevel;
  }


  /**
   * Sets the value of the 'customerLevel' field.
   * @param value the value to set.
   */
  public void setCustomerLevel(java.lang.String value) {
    this.customerLevel = value;
  }

  /**
   * Creates a new OrderEnriched RecordBuilder.
   * @return A new OrderEnriched RecordBuilder
   */
  public static io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder newBuilder() {
    return new io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder();
  }

  /**
   * Creates a new OrderEnriched RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderEnriched RecordBuilder
   */
  public static io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder newBuilder(io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder other) {
    if (other == null) {
      return new io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder();
    } else {
      return new io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder(other);
    }
  }

  /**
   * Creates a new OrderEnriched RecordBuilder by copying an existing OrderEnriched instance.
   * @param other The existing instance to copy.
   * @return A new OrderEnriched RecordBuilder
   */
  public static io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder newBuilder(io.confluent.examples.streams.avro.microservices.OrderEnriched other) {
    if (other == null) {
      return new io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder();
    } else {
      return new io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderEnriched instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderEnriched>
    implements org.apache.avro.data.RecordBuilder<OrderEnriched> {

    private java.lang.String id;
    private long customerId;
    private java.lang.String customerLevel;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.customerLevel)) {
        this.customerLevel = data().deepCopy(fields()[2].schema(), other.customerLevel);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderEnriched instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.examples.streams.avro.microservices.OrderEnriched other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customerLevel)) {
        this.customerLevel = data().deepCopy(fields()[2].schema(), other.customerLevel);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public long getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder setCustomerId(long value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder clearCustomerId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerLevel' field.
      * @return The value.
      */
    public java.lang.String getCustomerLevel() {
      return customerLevel;
    }


    /**
      * Sets the value of the 'customerLevel' field.
      * @param value The value of 'customerLevel'.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder setCustomerLevel(java.lang.String value) {
      validate(fields()[2], value);
      this.customerLevel = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'customerLevel' field has been set.
      * @return True if the 'customerLevel' field has been set, false otherwise.
      */
    public boolean hasCustomerLevel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'customerLevel' field.
      * @return This builder.
      */
    public io.confluent.examples.streams.avro.microservices.OrderEnriched.Builder clearCustomerLevel() {
      customerLevel = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderEnriched build() {
      try {
        OrderEnriched record = new OrderEnriched();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.Long) defaultValue(fields()[1]);
        record.customerLevel = fieldSetFlags()[2] ? this.customerLevel : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderEnriched>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderEnriched>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderEnriched>
    READER$ = (org.apache.avro.io.DatumReader<OrderEnriched>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeLong(this.customerId);

    out.writeString(this.customerLevel);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.customerId = in.readLong();

      this.customerLevel = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.customerId = in.readLong();
          break;

        case 2:
          this.customerLevel = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










