/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.streams.avro.microservices;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderValidationType {
  INVENTORY_CHECK, FRAUD_CHECK, ORDER_DETAILS_CHECK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderValidationType\",\"namespace\":\"io.confluent.examples.streams.avro.microservices\",\"symbols\":[\"INVENTORY_CHECK\",\"FRAUD_CHECK\",\"ORDER_DETAILS_CHECK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
